---
# For some reason, some of the NUCs keep falling asleep
- name: disable suspend and hibernate
  systemd:
    name: "{{ item }}"
    enabled: false
    masked: true
  with_items:
  - sleep.target
  - suspend.target
  - hibernate.target
  - hybrid-sleep.target
