---
- name: "Install fastfetch (aarch64)"
  apt:
    deb: "https://github.com/fastfetch-cli/fastfetch/releases/download/2.25.0/fastfetch-linux-aarch64.deb"
  when: ansible_architecture == "aarch64"

- name: "Install fastfetch (x86_64)"
  apt:
    deb: "https://github.com/fastfetch-cli/fastfetch/releases/download/2.25.0/fastfetch-linux-amd64.deb"
  when: ansible_architecture == "x86_64"
