---
- name: Add ssh keys to root
  authorized_key:
    user: root
    key: "{{ lookup('file', '../pubkeys/'+item+'.pub') }}"
  with_items: "{{ ssh_users }}"

- name: Configure root user
  user:
    name: root
    shell: /bin/bash
    password: ""
