---
- name: restart chrony
  systemd:
    daemon_reload: true
    name: chrony.service
    state: restarted

- name: reload ssh
  systemd:
    daemon_reload: true
    name: sshd
    state: reloaded

- name: update apt cache
  apt:
    update_cache: true

- name: restart network
  systemd:
    daemon_reload: true
    name: networking.service
    state: restarted

- name: reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system
  changed_when: false
